spring:
  datasource:
    username: root
    password: Mohamedd...012
    url: jdbc:mysql://127.0.0.1:3306/movies
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ezat71101@gmail.com
    password: lmiw ctpt uzjm gkzv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


project:
  poster: posters/
base:
  url: "http://localhost:8080"

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days